[package]
name = "kotlin-ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
uniffi_build = "0.28.0"

[dependencies]
yttrium = { path = "../yttrium" }
uniffi = "0.28.0"
openssl = { version = "0.10", features = ["vendored"] }
openssl-sys = { version = "0.9.103", features = ["vendored"] }
